version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  liquibase:
    container_name: liquibase
    image: liquibase/liquibase
    build:
      context: ./liquibase
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./liquibase/migrations.yaml:/liquibase/changelog/migrations.yaml
    command: "liquibase --url=jdbc:postgresql://postgres:5432/postgres --username=postgres --password=postgres --classpath=/liquibase/changelog --changeLogFile=migrations.yaml update"
    depends_on:
      - postgres
volumes:
  pgdata: {}