version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  liquibase:
    depends_on:
      - postgres
    container_name: liquibase
    image: liquibase/liquibase
    tty: true
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./liquibase/migrations.yaml:/liquibase/changelog/migrations.yaml
    command: bash -c 'echo N |liquibase
      --url=jdbc:postgresql://$${POSTGRES_HOST}:5432/$${POSTGRES_DB}
      --username=$${POSTGRES_USER}
      --password=$${POSTGRES_PASSWORD}
      --classpath=/liquibase/changelog
      --changeLogFile=migrations.yaml update'
volumes:
  pgdata: {}