version: "3.1"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  liquibase:
    container_name: liquibase
    image: liquibase/liquibase
    build:
      context: ./liquibase
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./liquibase/migrations.yaml:/liquibase/changelog/migrations.yaml
    depends_on:
      - postgres
volumes:
  pgdata: {}