on:
  pull_request:
    types: [opened, synchronize]

jobs:
  chatgpt-explain:
    runs-on: ubuntu-latest
    name: ChatGTP Explain Code
    steps:
      - name: ChatGTP Explain Code 🤖
        uses: cirolini/chatgpt-github-actions@v1
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}

  chatgpt-comment:
    runs-on: ubuntu-latest
    name: Let chatgpt comment on your PR 🤖
    steps:
      - name: ChatGPT comment
        uses: kxxt/chatgpt-action@v0.3
        id: chatgpt
        with:
          number: ${{ github.event.pull_request.number }}
          sessionToken: ${{ secrets.openai_api_key }}
          split: 'yolo'  # Use true to enable the unstable split feature.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}