name: feature

on:
  push:
    branches:
      - 'feature/**'


## feature tests
## release build-and-push, deploy
## hotfix tests , build-and-push, deploy
## main promote

jobs:
  env:
    uses: devxp-tech/.github/.github/workflows/env.yaml@main

  test:
    uses: devxp-tech/.github/.github/workflows/test.yaml@main

  quality-gate:
    uses: devxp-tech/.github/.github/workflows/sonarqube.yaml@main
    secrets: inherit

  code-scan:
    uses: devxp-tech/.github/.github/workflows/synk-golang.yaml@main
    secrets: inherit

  notify:
    uses: devxp-tech/.github/.github/workflows/notify.yaml@main
    if: always()
    secrets: inherit
    needs:
      - code-scan