name: feature

on:
  push:
    branches:
      - 'feature/**'

jobs:
  env:
    uses: devxp-tech/.github/.github/workflows/env.yaml@main

  test:
    uses: devxp-tech/.github/.github/workflows/test.yaml@main
    needs:
      - env

  quality-gate:
    uses: devxp-tech/.github/.github/workflows/sonarqube.yaml@main
    secrets: inherit
    needs:
      - env

  code-scan:
    uses: devxp-tech/.github/.github/workflows/synk-golang.yaml@main
    secrets: inherit
    needs:
      - env

  action-pull-request:
    runs-on: ubuntu-latest
    needs:
      - env
      - test
      - quality-gate
      - code-scan
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Push to Github
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b release/${GITHUB_REF#refs/*/}
        git push -u origin release/${GITHUB_REF#refs/*/}

    - name: Create Pull Request
      run: gh pr create --base release/${GITHUB_REF#refs/*/} --fill
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    uses: devxp-tech/.github/.github/workflows/notify.yaml@main
    if: always()
    secrets: inherit
    needs:
      - env
      - test
      - quality-gate
      - code-scan
      - action-pull-request