name: first-release

on:
  push:
    branches:
      - 'first-release/*'


jobs:
  env:
    uses: analect-io/.github/.github/workflows/env.yaml@main

  test:
    uses: analect-io/.github/.github/workflows/test.yaml@main

  quality-gate:
    uses: analect-io/.github/.github/workflows/sonarqube.yaml@main
    secrets: inherit

  build-and-push:
    uses: analect-io/.github/.github/workflows/build-and-push.yaml@main
    with:
      tag: ${{ needs.env.outputs.tag }}
    needs:
      - env
      - test
      - quality-gate

  security-gateway:
    uses: analect-io/.github/.github/workflows/trivy.yaml@main
    needs:
      - build-and-push

  deploy:
    uses: analect-io/.github/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      tag: ${{ needs.env.outputs.tag }}
      repository: ${{ needs.env.outputs.repository }}
    needs:
      - env
      - security-gateway

  notify:
    uses: analect-io/.github/.github/workflows/notify.yaml@main
    if: always()
    secrets: inherit
    needs:
      - deploy