name: liquibase
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "liquibase/**"

jobs:

  migrate:
    name: Run Liquibase Migration
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: ./docker-compose.yml
          service: liquibase