name: liquibase
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "liquibase/**"

jobs:

  migrate:
    name: Run Liquibase Migration
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
