name: main

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  env:
    uses: analect-io/.github/.github/workflows/env.yaml@main

  promote:
    uses: analect-io/.github/.github/workflows/promote.yaml@main
    secrets: inherit
    with:
      tag: ${{ needs.env.outputs.tag }}
      repository: ${{ needs.env.outputs.repository }}
      url: https://${{ needs.env.outputs.repository }}.analect-io.io
      environment: production
    needs:
      - env

  notify:
    uses: analect-io/.github/.github/workflows/notify.yaml@main
    if: always()
    secrets: inherit
    needs:
      - promote
