name: main

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  env:
    uses: devxp-tech/.github/.github/workflows/env.yaml@main

  promote:
    uses: devxp-tech/.github/.github/workflows/promote.yaml@main
    secrets: inherit
    with:
      tag: ${{ needs.env.outputs.tag }}
      repository: ${{ needs.env.outputs.repository }}
    needs:
      - env

  notify:
    uses: devxp-tech/.github/.github/workflows/notify.yaml@main
    if: always()
    secrets: inherit
    needs:
      - promote
