name: trivy

on:
  # the 1st condition
  workflow_run:
    workflows: ["tests", "build-and-push"]
    branches: [main]
    types:
      - completed

jobs:
  trivy:
    name: Trivy Scan 🔒
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner 🔎
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:${{ needs.vars.outputs.tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security Tab 📈
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'